"""CLI for ssh-concierge: generate, flush, list, status."""

from __future__ import annotations

import argparse
import fcntl
import os
import re
import shutil
import sys
import time
from pathlib import Path

from ssh_concierge import onepassword
from ssh_concierge.config import generate_runtime_config
from ssh_concierge.deploy import cmd_deploy_key
from ssh_concierge.expand import expand_host_config
from ssh_concierge.password import ItemMeta, build_op_reference


def _default_runtime_dir() -> Path:
    xdg = os.environ.get("XDG_RUNTIME_DIR")
    if xdg:
        return Path(xdg) / "ssh-concierge"
    return Path("/tmp") / f"ssh-concierge-{os.getuid()}"


def cmd_generate(runtime_dir: Path, *, quiet: bool = False) -> None:
    """Query 1Password and regenerate the runtime config."""
    runtime_dir.mkdir(parents=True, exist_ok=True)
    lock_path = runtime_dir / ".lock"

    with open(lock_path, "w") as lock_file:
        try:
            fcntl.flock(lock_file, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except OSError:
            # Another process holds the lock — check if config is now fresh
            conf = runtime_dir / "hosts.conf"
            if conf.exists():
                age = time.time() - conf.stat().st_mtime
                if age < 3600:
                    if not quiet:
                        print("Config is fresh (generated by another process)")
                    return  # Another process just regenerated
            # Wait for lock (blocking)
            fcntl.flock(lock_file, fcntl.LOCK_EX)
            # Double-check after acquiring lock
            if conf.exists():
                age = time.time() - conf.stat().st_mtime
                if age < 3600:
                    if not quiet:
                        print("Config is fresh (generated by another process)")
                    return

        if not quiet:
            print("Querying 1Password...")

        item_ids = onepassword.list_managed_item_ids()
        hosts = []
        password_refs: dict[str, str] = {}
        items_processed = 0
        for item_id in item_ids:
            item = onepassword.get_item(item_id)
            items_processed += 1
            meta = ItemMeta(
                vault_id=item.get('vault', {}).get('id', ''),
                item_id=item.get('id', ''),
            )
            for host in onepassword.parse_item_to_host_configs(item):
                for expanded in expand_host_config(host):
                    hosts.append(expanded)
                    if expanded.password and expanded.section_label:
                        ref = build_op_reference(expanded.password, meta, expanded.section_label)
                        for alias in expanded.aliases:
                            if '*' not in alias and '?' not in alias:
                                password_refs[alias] = ref

        generate_runtime_config(hosts, runtime_dir, password_refs or None)

        if not quiet:
            print(
                f"Generated: {len(hosts)} hosts from {items_processed} items"
                f" ({len(password_refs)} password-auth aliases)"
            )
            print(f"Config:    {runtime_dir / 'hosts.conf'}")
            if password_refs:
                print(f"Passwords: {runtime_dir / 'passwords.json'}")


def cmd_flush(runtime_dir: Path, *, quiet: bool = False) -> None:
    """Remove the runtime config directory."""
    if runtime_dir.exists():
        shutil.rmtree(runtime_dir)
        if not quiet:
            print(f"Removed {runtime_dir}")
    elif not quiet:
        print("Nothing to flush (no runtime config)")


def cmd_status(runtime_dir: Path) -> None:
    """Show config age, managed host count, staleness."""
    conf = runtime_dir / "hosts.conf"
    if not conf.exists():
        print("No config generated yet. Run: ssh-concierge --generate")
        return

    age_secs = time.time() - conf.stat().st_mtime
    content = conf.read_text()
    host_count = len(re.findall(r"^Host ", content, re.MULTILINE))

    age_min = int(age_secs // 60)
    stale = age_secs >= 3600
    status = "STALE" if stale else "fresh"

    print(f"Config: {conf}")
    print(f"Status: {status} (age: {age_min}m)")
    print(f"Managed hosts: {host_count}")


def cmd_list(runtime_dir: Path) -> None:
    """List all managed hosts from the generated config."""
    conf = runtime_dir / "hosts.conf"
    if not conf.exists():
        print("No config generated yet. Run: ssh-concierge --generate")
        return

    content = conf.read_text()
    for match in re.finditer(r"^Host (.+)$", content, re.MULTILINE):
        aliases = match.group(1)
        print(aliases)


def main() -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        prog="ssh-concierge",
        description="Dynamic SSH configuration provider backed by 1Password",
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--generate", action="store_true", help="Regenerate runtime config from 1Password")
    group.add_argument("--flush", action="store_true", help="Remove runtime config")
    group.add_argument("--list", action="store_true", help="List managed hosts")
    group.add_argument("--status", action="store_true", help="Show config status")
    group.add_argument("--deploy-key", metavar="ALIAS", help="Deploy SSH key to a host")

    parser.add_argument("--all", action="store_true", help="Deploy to all sibling hosts (only with --deploy-key)")
    parser.add_argument("-q", "--quiet", action="store_true", help="Suppress informational output")

    args = parser.parse_args()

    if args.all and not args.deploy_key:
        parser.error("--all can only be used with --deploy-key")

    runtime_dir = _default_runtime_dir()

    if args.generate:
        cmd_generate(runtime_dir, quiet=args.quiet)
    elif args.flush:
        cmd_flush(runtime_dir, quiet=args.quiet)
    elif args.list:
        cmd_list(runtime_dir)
    elif args.status:
        cmd_status(runtime_dir)
    elif args.deploy_key:
        cmd_deploy_key(args.deploy_key, args.all, runtime_dir)
