"""Runtime config generation — hosts.conf + public keys."""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path

from ssh_concierge.models import HostConfig

HEADER = "# Generated by ssh-concierge — do not edit"


def _safe_filename(fingerprint: str) -> str:
    """Sanitize a fingerprint for use as a filename (/ → _)."""
    return fingerprint.replace('/', '_')


def _escape_percent(value: str) -> str:
    """Escape literal % signs for SSH config token expansion (% → %%)."""
    return value.replace('%', '%%')


def generate_host_block(host: HostConfig, keys_dir: Path) -> str:
    """Generate a single SSH Host block from a HostConfig."""
    lines = [f"Host {host.host_pattern}"]
    lines.append(f"    HostName {host.effective_hostname}")

    if host.config_port:
        lines.append(f"    Port {host.config_port}")
    if host.config_user:
        lines.append(f"    User {_escape_percent(host.config_user)}")

    if host.public_key and host.fingerprint:
        key_path = keys_dir / f"{_safe_filename(host.fingerprint)}.pub"
        lines.append(f"    IdentityFile {key_path}")
        lines.append("    IdentitiesOnly yes")

    for directive, value in sorted(host.config_extra.items()):
        lines.append(f"    {directive} {_escape_percent(value)}")

    return "\n".join(lines) + "\n"


def generate_runtime_config(
    hosts: list[HostConfig],
    runtime_dir: Path,
    hostdata: dict[str, dict] | None = None,
) -> None:
    """Generate the complete runtime config: hosts.conf + key files + hostdata.json.

    Writes atomically via temp file + rename.
    hostdata maps alias → {fields: {name: {original, resolved, sensitive}}, clipboard, key}.
    """
    runtime_dir.mkdir(parents=True, exist_ok=True)
    keys_dir = runtime_dir / "keys"
    keys_dir.mkdir(exist_ok=True)

    # Dump public keys
    for host in hosts:
        if host.public_key and host.fingerprint:
            key_file = keys_dir / f"{_safe_filename(host.fingerprint)}.pub"
            _atomic_write(key_file, host.public_key + "\n")
            key_file.chmod(0o644)

    # Generate hosts.conf
    blocks = [HEADER]
    for host in hosts:
        blocks.append("")
        blocks.append(generate_host_block(host, keys_dir))

    content = "\n".join(blocks) if hosts else HEADER
    conf_path = runtime_dir / "hosts.conf"
    _atomic_write(conf_path, content)

    # Write hostdata.json (op:// references only, never plaintext)
    hd_path = runtime_dir / "hostdata.json"
    if hostdata:
        _atomic_write(hd_path, json.dumps(hostdata, indent=2) + "\n")
    elif hd_path.exists():
        hd_path.unlink()


def _atomic_write(path: Path, content: str) -> None:
    """Write content to path atomically using temp file + rename."""
    fd, tmp_path = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.")
    try:
        os.write(fd, content.encode())
        os.close(fd)
        os.rename(tmp_path, path)
    except BaseException:
        os.close(fd) if not os.get_inheritable(fd) else None
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise
