"""Runtime config generation — SSH config + public keys."""

from __future__ import annotations

import json
import os
import tempfile
from collections.abc import Callable
from pathlib import Path

from ssh_concierge.models import HostConfig

HEADER = "# Generated by ssh-concierge — do not edit"


def _escape_percent(value: str) -> str:
    r"""Convert \% (literal percent marker) to %% for SSH config."""
    return value.replace('\\%', '%%')


def generate_host_block(
    host: HostConfig,
    key_file: Callable[[str], Path],
) -> str:
    """Generate a single SSH Host block from a HostConfig.

    key_file maps a fingerprint string to the public key file path.
    """
    lines = [f"Host {host.host_pattern}"]
    lines.append(f"    HostName {host.effective_hostname}")

    if host.config_port:
        lines.append(f"    Port {host.config_port}")
    if host.config_user:
        lines.append(f"    User {_escape_percent(host.config_user)}")

    if host.public_key and host.fingerprint:
        lines.append(f"    IdentityFile {key_file(host.fingerprint)}")

    for directive, value in sorted(host.config_extra.items()):
        lines.append(f"    {directive} {_escape_percent(value)}")

    return "\n".join(lines) + "\n"


def generate_runtime_config(
    hosts: list[HostConfig],
    *,
    runtime_dir: Path,
    keys_dir: Path,
    hosts_file: Path,
    hostdata_file: Path,
    key_file: Callable[[str], Path],
    hostdata: dict[str, dict] | None = None,
    key_mode: int = 0o600,
) -> None:
    """Generate the complete runtime config: SSH config + key files + host data cache.

    Writes atomically via temp file + rename.
    hostdata maps alias → {fields: {name: {original, resolved, sensitive}}, clipboard, key}.
    """
    runtime_dir.mkdir(parents=True, exist_ok=True)
    keys_dir.mkdir(exist_ok=True)

    # Dump public keys
    for host in hosts:
        if host.public_key and host.fingerprint:
            kf = key_file(host.fingerprint)
            _atomic_write(kf, host.public_key + "\n")
            kf.chmod(key_mode)

    # Generate SSH config
    blocks = [HEADER]
    for host in hosts:
        blocks.append("")
        blocks.append(generate_host_block(host, key_file))

    content = "\n".join(blocks) if hosts else HEADER
    _atomic_write(hosts_file, content)

    # Write host data cache (op:// references only, never plaintext)
    if hostdata:
        _atomic_write(hostdata_file, json.dumps(hostdata, indent=2) + "\n")
    elif hostdata_file.exists():
        hostdata_file.unlink()


def _atomic_write(path: Path, content: str) -> None:
    """Write content to path atomically using temp file + rename."""
    fd, tmp_path = tempfile.mkstemp(dir=path.parent, prefix=f'.{path.name}.')
    try:
        os.write(fd, content.encode())
        os.close(fd)
        os.rename(tmp_path, path)
    except BaseException:
        try:
            os.close(fd)
        except OSError:
            pass
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise
