"""Tests for ssh_concierge.cli."""

import json
import os
from pathlib import Path
from unittest.mock import patch, MagicMock

import pytest

from ssh_concierge.cli import cmd_generate, cmd_flush, cmd_status, cmd_list, main
from ssh_concierge.deploy import cmd_deploy_key
from ssh_concierge.models import HostConfig
from ssh_concierge.onepassword import OpError


@pytest.fixture()
def runtime_dir(tmp_path: Path) -> Path:
    """Provide a temporary runtime directory."""
    return tmp_path / "ssh-concierge"


SAMPLE_HOSTS = [
    HostConfig(
        aliases=["prod", "prod-web"],
        hostname="10.0.0.1",
        port="22",
        user="deploy",
        public_key="ssh-ed25519 AAAAprod prod-key",
        fingerprint="SHA256:prodkey",
    ),
    HostConfig(
        aliases=["bastion"],
        hostname="10.0.0.254",
        public_key="ssh-rsa AAAAbastion bastion-key",
        fingerprint="SHA256:bastionkey",
    ),
]


class TestCmdGenerate:
    @patch("ssh_concierge.cli.onepassword")
    def test_generates_config(self, mock_op, runtime_dir: Path):
        mock_op.list_managed_item_ids.return_value = ["id1", "id2"]
        mock_op.get_item.side_effect = [
            {"id": "id1", "fields": _make_item_fields(SAMPLE_HOSTS[0])},
            {"id": "id2", "fields": _make_item_fields(SAMPLE_HOSTS[1])},
        ]
        mock_op.parse_item_to_host_configs.side_effect = [[SAMPLE_HOSTS[0]], [SAMPLE_HOSTS[1]]]

        cmd_generate(runtime_dir)

        conf = runtime_dir / "hosts.conf"
        assert conf.exists()
        content = conf.read_text()
        assert "Host prod prod-web" in content
        assert "Host bastion" in content

    @patch("ssh_concierge.cli.onepassword")
    def test_skips_unparseable_items(self, mock_op, runtime_dir: Path):
        mock_op.list_managed_item_ids.return_value = ["id1"]
        mock_op.get_item.return_value = {"id": "id1", "fields": []}
        mock_op.parse_item_to_host_configs.return_value = []

        cmd_generate(runtime_dir)

        conf = runtime_dir / "hosts.conf"
        assert conf.exists()
        # Only header, no Host blocks
        assert "Host " not in conf.read_text()

    @patch("ssh_concierge.cli.onepassword")
    def test_op_error_raises(self, mock_op, runtime_dir: Path):
        mock_op.list_managed_item_ids.side_effect = OpError("not signed in")
        with pytest.raises(OpError):
            cmd_generate(runtime_dir)


class TestCmdFlush:
    def test_removes_runtime_dir(self, runtime_dir: Path):
        runtime_dir.mkdir(parents=True)
        (runtime_dir / "hosts.conf").write_text("test")
        keys_dir = runtime_dir / "keys"
        keys_dir.mkdir()
        (keys_dir / "key.pub").write_text("key")

        cmd_flush(runtime_dir)

        assert not runtime_dir.exists()

    def test_flush_nonexistent_is_noop(self, runtime_dir: Path):
        cmd_flush(runtime_dir)  # should not raise


class TestCmdStatus:
    def test_no_config(self, runtime_dir: Path, capsys):
        cmd_status(runtime_dir)
        output = capsys.readouterr().out
        assert "not generated" in output.lower() or "no config" in output.lower()

    def test_with_config(self, runtime_dir: Path, capsys):
        runtime_dir.mkdir(parents=True)
        conf = runtime_dir / "hosts.conf"
        conf.write_text("# Generated by ssh-concierge\n\nHost prod\n    HostName 10.0.0.1\n")

        cmd_status(runtime_dir)
        output = capsys.readouterr().out
        assert "1" in output  # 1 host


class TestCmdList:
    def test_list_hosts(self, runtime_dir: Path, capsys):
        runtime_dir.mkdir(parents=True)
        conf = runtime_dir / "hosts.conf"
        conf.write_text(
            "# Generated by ssh-concierge\n\n"
            "Host prod prod-web\n    HostName 10.0.0.1\n\n"
            "Host bastion\n    HostName 10.0.0.254\n"
        )

        cmd_list(runtime_dir)
        output = capsys.readouterr().out
        assert "prod" in output
        assert "bastion" in output

    def test_list_no_config(self, runtime_dir: Path, capsys):
        cmd_list(runtime_dir)
        output = capsys.readouterr().out
        assert "not generated" in output.lower() or "no config" in output.lower()


class TestMain:
    @patch("ssh_concierge.cli.cmd_generate")
    def test_generate_flag(self, mock_gen):
        with patch("sys.argv", ["ssh-concierge", "--generate"]):
            main()
        mock_gen.assert_called_once()

    @patch("ssh_concierge.cli.cmd_flush")
    def test_flush_flag(self, mock_flush):
        with patch("sys.argv", ["ssh-concierge", "--flush"]):
            main()
        mock_flush.assert_called_once()

    @patch("ssh_concierge.cli.cmd_status")
    def test_status_flag(self, mock_status):
        with patch("sys.argv", ["ssh-concierge", "--status"]):
            main()
        mock_status.assert_called_once()

    @patch("ssh_concierge.cli.cmd_list")
    def test_list_flag(self, mock_list):
        with patch("sys.argv", ["ssh-concierge", "--list"]):
            main()
        mock_list.assert_called_once()

    @patch("ssh_concierge.cli.cmd_deploy_key")
    def test_deploy_key_flag(self, mock_deploy):
        with patch("sys.argv", ["ssh-concierge", "--deploy-key", "worker1"]):
            main()
        mock_deploy.assert_called_once()
        args = mock_deploy.call_args
        assert args[0][0] == "worker1"
        assert args[0][1] is False  # --all not set

    @patch("ssh_concierge.cli.cmd_deploy_key")
    def test_deploy_key_with_all(self, mock_deploy):
        with patch("sys.argv", ["ssh-concierge", "--deploy-key", "worker1", "--all"]):
            main()
        mock_deploy.assert_called_once()
        args = mock_deploy.call_args
        assert args[0][0] == "worker1"
        assert args[0][1] is True  # --all set

    def test_all_without_deploy_key_fails(self):
        with patch("sys.argv", ["ssh-concierge", "--list", "--all"]):
            with pytest.raises(SystemExit):
                main()


def _make_item_fields(host: HostConfig) -> list[dict]:
    """Helper to create op item fields dict from a HostConfig."""
    fields = []
    if host.public_key:
        fields.append({"id": "public_key", "label": "public key", "value": host.public_key})
    if host.fingerprint:
        fields.append({"id": "fingerprint", "label": "fingerprint", "value": host.fingerprint})
    fields.append({
        "id": "aliases",
        "label": "aliases",
        "value": ", ".join(host.aliases),
        "section": {"id": "sshconfig", "label": "SSH Config"},
    })
    if host.hostname:
        fields.append({
            "id": "hostname",
            "label": "hostname",
            "value": host.hostname,
            "section": {"id": "sshconfig", "label": "SSH Config"},
        })
    return fields
