"""Tests for ssh_concierge.cli."""

import json
import os
from pathlib import Path
from unittest.mock import patch, MagicMock

from tests.conftest import fv

import pytest

from ssh_concierge.cli import (
    cmd_generate, cmd_flush, cmd_status, cmd_list, cmd_debug, main,
    _parse_op_item_ref, _build_key_registry, _resolve_key_ref,
    _load_cached_hostdata,
)
from ssh_concierge.deploy import cmd_deploy_key
from ssh_concierge.models import HostConfig
from ssh_concierge.onepassword import OpError


@pytest.fixture()
def runtime_dir(tmp_path: Path) -> Path:
    """Provide a temporary runtime directory."""
    return tmp_path / "ssh-concierge"


SAMPLE_HOSTS = [
    HostConfig(
        aliases=["prod", "prod-web"],
        hostname=fv("10.0.0.1", "hostname"),
        port=fv("22", "port"),
        user=fv("deploy", "user"),
        public_key="ssh-ed25519 AAAAprod prod-key",
        fingerprint="SHA256:prodkey",
    ),
    HostConfig(
        aliases=["bastion"],
        hostname=fv("10.0.0.254", "hostname"),
        public_key="ssh-rsa AAAAbastion bastion-key",
        fingerprint="SHA256:bastionkey",
    ),
]


class TestCmdGenerate:
    @patch("ssh_concierge.cli.OnePassword")
    def test_generates_config(self, mock_op_cls, runtime_dir: Path):
        mock_op = mock_op_cls.return_value
        mock_op.list_managed_item_ids.return_value = ["id1", "id2"]
        mock_op.get_item.side_effect = [
            {"id": "id1", "vault": {"id": "v1"}, "fields": []},
            {"id": "id2", "vault": {"id": "v2"}, "fields": []},
        ]

        with patch("ssh_concierge.cli.parse_item_to_host_configs") as mock_parse:
            mock_parse.side_effect = [[SAMPLE_HOSTS[0]], [SAMPLE_HOSTS[1]]]
            cmd_generate(runtime_dir)

        conf = runtime_dir / "hosts.conf"
        assert conf.exists()
        content = conf.read_text()
        assert "Host prod prod-web" in content
        assert "Host bastion" in content

    @patch("ssh_concierge.cli.OnePassword")
    def test_skips_unparseable_items(self, mock_op_cls, runtime_dir: Path):
        mock_op = mock_op_cls.return_value
        mock_op.list_managed_item_ids.return_value = ["id1"]
        mock_op.get_item.return_value = {"id": "id1", "vault": {"id": "v1"}, "fields": []}

        with patch("ssh_concierge.cli.parse_item_to_host_configs") as mock_parse:
            mock_parse.return_value = []
            cmd_generate(runtime_dir)

        conf = runtime_dir / "hosts.conf"
        assert conf.exists()
        # Only header, no Host blocks
        assert "Host " not in conf.read_text()

    @patch("ssh_concierge.cli.OnePassword")
    def test_op_error_raises(self, mock_op_cls, runtime_dir: Path):
        mock_op = mock_op_cls.return_value
        mock_op.list_managed_item_ids.side_effect = OpError("not signed in")
        with pytest.raises(OpError):
            cmd_generate(runtime_dir)


class TestCmdFlush:
    def test_removes_runtime_dir(self, runtime_dir: Path):
        runtime_dir.mkdir(parents=True)
        (runtime_dir / "hosts.conf").write_text("test")
        keys_dir = runtime_dir / "keys"
        keys_dir.mkdir()
        (keys_dir / "key.pub").write_text("key")

        cmd_flush(runtime_dir)

        assert not runtime_dir.exists()

    def test_flush_nonexistent_is_noop(self, runtime_dir: Path):
        cmd_flush(runtime_dir)  # should not raise


class TestCmdStatus:
    def test_no_config(self, runtime_dir: Path, capsys):
        cmd_status(runtime_dir)
        output = capsys.readouterr().out
        assert "not generated" in output.lower() or "no config" in output.lower()

    def test_with_config(self, runtime_dir: Path, capsys):
        runtime_dir.mkdir(parents=True)
        conf = runtime_dir / "hosts.conf"
        conf.write_text("# Generated by ssh-concierge\n\nHost prod\n    HostName 10.0.0.1\n")

        cmd_status(runtime_dir)
        output = capsys.readouterr().out
        assert "1" in output  # 1 host


class TestCmdList:
    def test_list_hosts(self, runtime_dir: Path, capsys):
        runtime_dir.mkdir(parents=True)
        conf = runtime_dir / "hosts.conf"
        conf.write_text(
            "# Generated by ssh-concierge\n\n"
            "Host prod prod-web\n    HostName 10.0.0.1\n\n"
            "Host bastion\n    HostName 10.0.0.254\n"
        )

        cmd_list(runtime_dir)
        output = capsys.readouterr().out
        assert "prod" in output
        assert "bastion" in output

    def test_list_no_config(self, runtime_dir: Path, capsys):
        cmd_list(runtime_dir)
        output = capsys.readouterr().out
        assert "not generated" in output.lower() or "no config" in output.lower()


SAMPLE_HOSTS_CONF = (
    "# Generated by ssh-concierge\n\n"
    "Host prod prod-web-01\n"
    "    HostName 203.0.113.42\n"
    "    Port 2222\n"
    "    User deploy\n"
    "    IdentityFile /run/user/1000/ssh-concierge/keys/SHA256:abc123.pub\n"
    "    IdentitiesOnly yes\n"
    "    ProxyJump bastion\n\n"
    "Host bastion\n"
    "    HostName 10.0.0.254\n"
    "    IdentityFile /run/user/1000/ssh-concierge/keys/SHA256:bastionkey.pub\n"
    "    IdentitiesOnly yes\n"
)

SAMPLE_HOSTDATA = {
    "prod": {
        "fields": {
            "password": {"original": "op://Work/ServerLogin/password", "resolved": None, "sensitive": True},
        },
    },
    "prod-web-01": {
        "fields": {
            "password": {"original": "op://Work/ServerLogin/password", "resolved": None, "sensitive": True},
        },
    },
}


class TestCmdDebug:
    def test_alias_found_outputs_host_block(self, runtime_dir: Path, capsys):
        runtime_dir.mkdir(parents=True)
        (runtime_dir / "hosts.conf").write_text(SAMPLE_HOSTS_CONF)

        cmd_debug("prod", runtime_dir)
        output = capsys.readouterr().out

        assert "Host prod prod-web-01" in output
        assert "HostName 203.0.113.42" in output
        assert "Port 2222" in output
        assert "User deploy" in output
        assert "ProxyJump bastion" in output

    def test_alias_not_found(self, runtime_dir: Path, capsys):
        runtime_dir.mkdir(parents=True)
        (runtime_dir / "hosts.conf").write_text(SAMPLE_HOSTS_CONF)

        cmd_debug("nonexistent", runtime_dir)
        output = capsys.readouterr().out

        assert "not found" in output.lower()

    def test_no_config(self, runtime_dir: Path, capsys):
        cmd_debug("prod", runtime_dir)
        output = capsys.readouterr().out

        assert "no config" in output.lower()

    def test_alias_with_password_reference(self, runtime_dir: Path, capsys):
        runtime_dir.mkdir(parents=True)
        (runtime_dir / "hosts.conf").write_text(SAMPLE_HOSTS_CONF)
        (runtime_dir / "hostdata.json").write_text(json.dumps(SAMPLE_HOSTDATA))

        cmd_debug("prod", runtime_dir)
        output = capsys.readouterr().out

        assert "op://Work/ServerLogin/password" in output

    def test_alias_without_password(self, runtime_dir: Path, capsys):
        runtime_dir.mkdir(parents=True)
        (runtime_dir / "hosts.conf").write_text(SAMPLE_HOSTS_CONF)

        cmd_debug("bastion", runtime_dir)
        output = capsys.readouterr().out

        assert "Host bastion" in output
        assert "Password" not in output

    def test_multi_alias_matches_any(self, runtime_dir: Path, capsys):
        runtime_dir.mkdir(parents=True)
        (runtime_dir / "hosts.conf").write_text(SAMPLE_HOSTS_CONF)

        cmd_debug("prod-web-01", runtime_dir)
        output = capsys.readouterr().out

        assert "Host prod prod-web-01" in output
        assert "HostName 203.0.113.42" in output

    def test_alias_with_clipboard(self, runtime_dir: Path, capsys):
        runtime_dir.mkdir(parents=True)
        (runtime_dir / "hosts.conf").write_text(SAMPLE_HOSTS_CONF)
        hd = {
            "prod": {
                "fields": {
                    "password": {"original": "op://Work/ServerLogin/password", "resolved": None, "sensitive": True},
                },
                "clipboard": "sudo -i\\n{password}\\n",
            },
        }
        (runtime_dir / "hostdata.json").write_text(json.dumps(hd))

        cmd_debug("prod", runtime_dir)
        output = capsys.readouterr().out

        assert "Password:" in output
        assert "Clipboard:" in output

    def test_config_age_shown(self, runtime_dir: Path, capsys):
        runtime_dir.mkdir(parents=True)
        (runtime_dir / "hosts.conf").write_text(SAMPLE_HOSTS_CONF)

        cmd_debug("prod", runtime_dir)
        output = capsys.readouterr().out

        assert "config age" in output.lower()


class TestMain:
    @patch("ssh_concierge.cli.cmd_generate")
    def test_generate_flag(self, mock_gen):
        with patch("sys.argv", ["ssh-concierge", "--generate"]):
            main()
        mock_gen.assert_called_once()

    @patch("ssh_concierge.cli.cmd_flush")
    def test_flush_flag(self, mock_flush):
        with patch("sys.argv", ["ssh-concierge", "--flush"]):
            main()
        mock_flush.assert_called_once()

    @patch("ssh_concierge.cli.cmd_status")
    def test_status_flag(self, mock_status):
        with patch("sys.argv", ["ssh-concierge", "--status"]):
            main()
        mock_status.assert_called_once()

    @patch("ssh_concierge.cli.cmd_list")
    def test_list_flag(self, mock_list):
        with patch("sys.argv", ["ssh-concierge", "--list"]):
            main()
        mock_list.assert_called_once()

    @patch("ssh_concierge.cli.cmd_debug")
    def test_debug_flag(self, mock_debug):
        with patch("sys.argv", ["ssh-concierge", "--debug", "prod"]):
            main()
        mock_debug.assert_called_once()
        assert mock_debug.call_args[0][0] == "prod"

    @patch("ssh_concierge.cli.cmd_deploy_key")
    def test_deploy_key_flag(self, mock_deploy):
        with patch("sys.argv", ["ssh-concierge", "--deploy-key", "worker1"]):
            main()
        mock_deploy.assert_called_once()
        args = mock_deploy.call_args
        assert args[0][0] == "worker1"
        assert args[0][1] is False  # --all not set

    @patch("ssh_concierge.cli.cmd_deploy_key")
    def test_deploy_key_with_all(self, mock_deploy):
        with patch("sys.argv", ["ssh-concierge", "--deploy-key", "worker1", "--all"]):
            main()
        mock_deploy.assert_called_once()
        args = mock_deploy.call_args
        assert args[0][0] == "worker1"
        assert args[0][1] is True  # --all set

    def test_all_without_deploy_key_fails(self):
        with patch("sys.argv", ["ssh-concierge", "--list", "--all"]):
            with pytest.raises(SystemExit):
                main()

    @patch("ssh_concierge.cli.cmd_generate")
    def test_no_cache_flag(self, mock_gen):
        with patch("sys.argv", ["ssh-concierge", "--generate", "--no-cache"]):
            main()
        mock_gen.assert_called_once()
        kwargs = mock_gen.call_args[1]
        assert kwargs['no_cache'] is True

    def test_no_cache_without_generate_fails(self):
        with patch("sys.argv", ["ssh-concierge", "--list", "--no-cache"]):
            with pytest.raises(SystemExit):
                main()


class TestLoadCachedHostdata:
    def test_no_file(self, runtime_dir: Path):
        assert _load_cached_hostdata(runtime_dir) == {}

    def test_empty_file(self, runtime_dir: Path):
        runtime_dir.mkdir(parents=True)
        (runtime_dir / 'hostdata.json').write_text('{}')
        assert _load_cached_hostdata(runtime_dir) == {}

    def test_loads_fields(self, runtime_dir: Path):
        runtime_dir.mkdir(parents=True)
        hd = {
            'myhost': {
                'fields': {
                    'hostname': {'original': 'op://V/I/hostname', 'resolved': '10.0.0.1', 'sensitive': False},
                    'password': {'original': 'ops://V/I/pw', 'resolved': None, 'sensitive': True},
                },
            },
        }
        (runtime_dir / 'hostdata.json').write_text(json.dumps(hd))
        result = _load_cached_hostdata(runtime_dir)
        assert 'myhost' in result
        assert result['myhost']['hostname'].original == 'op://V/I/hostname'
        assert result['myhost']['hostname'].resolved == '10.0.0.1'
        assert result['myhost']['password'].sensitive is True

    def test_skips_entries_without_fields(self, runtime_dir: Path):
        runtime_dir.mkdir(parents=True)
        hd = {
            'myhost': {'clipboard': 'hello'},
        }
        (runtime_dir / 'hostdata.json').write_text(json.dumps(hd))
        result = _load_cached_hostdata(runtime_dir)
        assert 'myhost' not in result

    def test_bad_json(self, runtime_dir: Path):
        runtime_dir.mkdir(parents=True)
        (runtime_dir / 'hostdata.json').write_text('not json')
        assert _load_cached_hostdata(runtime_dir) == {}


class TestParseOpItemRef:
    def test_valid_reference(self):
        assert _parse_op_item_ref('op://Work/MyKey') == ('Work', 'MyKey')

    def test_vault_with_spaces(self):
        assert _parse_op_item_ref('op://My Vault/Key Name') == ('My Vault', 'Key Name')

    def test_no_prefix_still_parses(self):
        """Without op:// prefix the string is split as-is."""
        assert _parse_op_item_ref('Work/MyKey') == ('Work', 'MyKey')

    def test_invalid_no_slash(self):
        with pytest.raises(ValueError):
            _parse_op_item_ref('op://WorkMyKey')

    def test_invalid_empty_vault(self):
        with pytest.raises(ValueError):
            _parse_op_item_ref('op:///MyKey')

    def test_invalid_empty_title(self):
        with pytest.raises(ValueError):
            _parse_op_item_ref('op://Work/')


class TestBuildKeyRegistry:
    def test_builds_from_items(self):
        items = [
            {
                'id': 'key1',
                'title': 'My SSH Key',
                'vault': {'id': 'v1', 'name': 'Work'},
                'fields': [
                    {'label': 'public key', 'value': 'ssh-ed25519 AAAA'},
                    {'label': 'fingerprint', 'value': 'SHA256:abc'},
                ],
            },
        ]
        registry = _build_key_registry(items)
        assert ('work', 'my ssh key') in registry
        assert registry[('work', 'my ssh key')] == ('ssh-ed25519 AAAA', 'SHA256:abc')
        assert ('key1',) in registry

    def test_skips_items_without_key_data(self):
        items = [
            {
                'id': 'nokey',
                'title': 'Server',
                'vault': {'id': 'v1', 'name': 'Work'},
                'fields': [],
            },
        ]
        registry = _build_key_registry(items)
        assert len(registry) == 0

    def test_skips_section_fields(self):
        """Only item-level (no section) public_key/fingerprint are used."""
        items = [
            {
                'id': 'key1',
                'title': 'Key',
                'vault': {'id': 'v1', 'name': 'Work'},
                'fields': [
                    {'label': 'public key', 'value': 'ssh-ed25519 AAAA',
                     'section': {'id': 's', 'label': 'SSH Config'}},
                    {'label': 'fingerprint', 'value': 'SHA256:abc',
                     'section': {'id': 's', 'label': 'SSH Config'}},
                ],
            },
        ]
        registry = _build_key_registry(items)
        assert len(registry) == 0

    def test_multiple_items(self):
        items = [
            {
                'id': 'k1', 'title': 'Key A', 'vault': {'id': 'v1', 'name': 'Work'},
                'fields': [
                    {'label': 'public key', 'value': 'ssh-ed25519 AAAA-A'},
                    {'label': 'fingerprint', 'value': 'SHA256:aaa'},
                ],
            },
            {
                'id': 'k2', 'title': 'Key B', 'vault': {'id': 'v2', 'name': 'Personal'},
                'fields': [
                    {'label': 'public key', 'value': 'ssh-rsa AAAA-B'},
                    {'label': 'fingerprint', 'value': 'SHA256:bbb'},
                ],
            },
        ]
        registry = _build_key_registry(items)
        assert registry[('work', 'key a')] == ('ssh-ed25519 AAAA-A', 'SHA256:aaa')
        assert registry[('personal', 'key b')] == ('ssh-rsa AAAA-B', 'SHA256:bbb')


class TestResolveKeyRef:
    def _registry(self):
        return {
            ('work', 'my ssh key'): ('ssh-ed25519 AAAA', 'SHA256:abc'),
            ('k1',): ('ssh-ed25519 AAAA', 'SHA256:abc'),
        }

    def test_resolves_key_ref(self):
        host = HostConfig(
            aliases=['myhost'],
            hostname=fv('10.0.0.1', 'hostname'),
            key_ref='op://Work/My SSH Key',
        )
        result = _resolve_key_ref(host, self._registry())
        assert result.public_key == 'ssh-ed25519 AAAA'
        assert result.fingerprint == 'SHA256:abc'
        assert result.key_ref == 'op://Work/My SSH Key'  # preserved

    def test_already_has_public_key(self):
        """key_ref is ignored when host already has a public_key."""
        host = HostConfig(
            aliases=['myhost'],
            hostname=fv('10.0.0.1', 'hostname'),
            public_key='ssh-rsa existing',
            fingerprint='SHA256:existing',
            key_ref='op://Work/My SSH Key',
        )
        result = _resolve_key_ref(host, self._registry())
        assert result.public_key == 'ssh-rsa existing'
        assert result.fingerprint == 'SHA256:existing'

    def test_no_key_ref(self):
        host = HostConfig(aliases=['myhost'], hostname=fv('10.0.0.1', 'hostname'))
        result = _resolve_key_ref(host, self._registry())
        assert result is host  # unchanged

    def test_key_not_found(self, capsys):
        host = HostConfig(
            aliases=['myhost'],
            hostname=fv('10.0.0.1', 'hostname'),
            key_ref='op://Work/Nonexistent',
        )
        result = _resolve_key_ref(host, self._registry())
        assert result.public_key is None
        assert result.fingerprint is None
        err = capsys.readouterr().err
        assert 'not found' in err

    def test_invalid_ref(self, capsys):
        host = HostConfig(
            aliases=['myhost'],
            hostname=fv('10.0.0.1', 'hostname'),
            key_ref='not-a-valid-ref',
        )
        result = _resolve_key_ref(host, self._registry())
        assert result.public_key is None
        err = capsys.readouterr().err
        assert 'invalid key reference' in err

    def test_case_insensitive_lookup(self):
        host = HostConfig(
            aliases=['myhost'],
            hostname=fv('10.0.0.1', 'hostname'),
            key_ref='op://WORK/MY SSH KEY',
        )
        result = _resolve_key_ref(host, self._registry())
        assert result.public_key == 'ssh-ed25519 AAAA'


class TestCmdDebugKeyRef:
    def test_alias_with_key_reference(self, runtime_dir: Path, capsys):
        runtime_dir.mkdir(parents=True)
        (runtime_dir / 'hosts.conf').write_text(SAMPLE_HOSTS_CONF)
        hd = {
            'prod': {
                'key': 'op://Work/ProdKey',
                'fields': {
                    'password': {'original': 'op://Work/ServerLogin/password', 'resolved': None, 'sensitive': True},
                },
            },
        }
        (runtime_dir / 'hostdata.json').write_text(json.dumps(hd))

        cmd_debug('prod', runtime_dir)
        output = capsys.readouterr().out

        assert 'Key: op://Work/ProdKey' in output
        assert 'Password:' in output
